Update rustup
This may be required to avoid this issue:
  error: no such command: `fmt`

See https://rust-lang.github.io/rustup/basics.html#keeping-rustup-up-to-date

Signed-off-by: Mickaël Salaün <mic@digikod.net>